const express = require("express")
const route = require('./routers/routers')
const {sequelize} = require('./models/models')
const port = require('./config')
const app = express()
app.use(express.json())
sequelize.sync({force:false})
.then(()=> console.log('ok'))
.catch(err =>console.log(err))
app.use(route)
app.listen(port,console.log(9000))