const express = require("express")
const route = require('./routers/routers')
const {sequelize} = require('./models/models')
const PORT= require('./config')
const cors = require('cors')
const app = express()
app.use(cors())
app.use(express.json())
sequelize.sync({force:false})
.then(()=> console.log('ok'))
.catch(err =>console.log(err))
app.use(route)
app.listen(PORT,console.log(9000))